"""create customers table

Revision ID: 30763536f4ab
Revises: 
Create Date: 2026-04-30 20:21:51.027490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30763536f4ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('sales_rep', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
